#! /bin/sh

DEV1='wan6'
uci set system.@led[0]=led
uci set system.@led[0].sysfs='white:power'
uci set system.@led[0].trigger='netdev'
uci set system.@led[0].dev='wan'
uci ad_list system.@led[0].mode='link'
uci set system.@led[1]=led
uci set system.@led[1].sysfs='red:power'
uci set system.@led[1].trigger='netdev'
uci set system.@led[1].dev=${DEV1}
uci ad_list system.@led[1].mode='tx'
uci ad_list system.@led[1].mode='rx'
uci set system.@led[2]=led
uci set system.@led[2].sysfs='red:router'
uci set system.@led[2].trigger='usbport'
uci ad_list system.@led[2].port='usb1-port1'
uci ad_list system.@led[2].port='usb2-port1'
uci set system.@led[3]=led
uci set system.@led[3].sysfs='white:internet'
uci set system.@led[3].trigger='netdev'
uci set system.@led[3].dev='phy1-ap0'
uci ad_list system.@led[3].mode='link'
uci set system.@led[4]=led
uci set system.@led[4].sysfs='red:internet'
uci set system.@led[4].trigger='netdev'
uci set system.@led[4].dev='phy1-ap0'
uci ad_list system.@led[4].mode='tx'
uci ad_list system.@led[4].mode='rx'
uci set system.@led[5]=led
uci set system.@led[5].sysfs='white:wireless'
uci set system.@led[5].trigger='netdev'
uci set system.@led[5].dev='phy0-ap0'
uci ad_list system.@led[5].mode='link'
uci set system.@led[6]=led
uci set system.@led[6].sysfs='red:wireless'
uci set system.@led[6].trigger='netdev'
uci set system.@led[6].dev='phy0-ap0'
uci ad_list system.@led[6].mode='tx'
uci ad_list system.@led[6].mode='rx'
uci commit system
service system restart
